### ISSUE TITLE
Feature Request: Merge VSCode configurations into existing settings

### ISSUE THREAD

**Issue by BenBE** [patrislav1/ioc2cmake#3]
It would be cool if the existing settings of .vscode for especially the `launch.json` could be kept and just supplemented by the settings defined in the Python script. Especially if you have a somewhat mixed project with an CubeMX project as well as some python code, it's a bit annoying to always have to reconfigure the Python debugging configuration.

**Comment by patrislav1** [comment]
maybe upgrade to [cubemx.cmake](https://github.com/patrislav1/cubemx.cmake) and use a custom [vscode-debug.in](https://github.com/patrislav1/cubemx.cmake/blob/master/cmake/stlink/vscode-debug.in)?

**Comment by BenBE** [comment]
Is there some migration guide available?

**Comment by patrislav1** [comment]
I suggest adding your application sources to [CMakeLists-example.txt](https://github.com/patrislav1/cubemx.cmake/blob/master/CMakeLists-example.txt), verify compiler/linker settings with `make VERBOSE=1`, add custom options / targets as needed.

**Comment by patrislav1** [comment]
Another, maybe easier/quicker solution would be to disable the `.vscode` file generation completely (remove `-v` option), make the paths in the config files relative (using `${workspaceRoot}`), check them in, manage them manually.
